/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csa_application.gui;

import java.awt.Color;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/**
 *
 * @author Kit
 */
public class BroadcastPanel extends javax.swing.JPanel {

    /**
     * Creates new form BroadcastPanel
     */
    public BroadcastPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contentArea = new javax.swing.JTextArea();
        twitterButton = new javax.swing.JRadioButton();
        emailButton = new javax.swing.JRadioButton();
        count = new javax.swing.JLabel();

        contentArea.setColumns(20);
        contentArea.setFont(new java.awt.Font("Kartika", 0, 10)); // NOI18N
        contentArea.setRows(5);
        contentArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contentAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(contentArea);

        twitterButton.setFont(new java.awt.Font("Kartika", 0, 14)); // NOI18N
        twitterButton.setText("Twitter");

        emailButton.setFont(new java.awt.Font("Kartika", 0, 14)); // NOI18N
        emailButton.setText("Email");

        count.setFont(new java.awt.Font("Kartika", 0, 14)); // NOI18N
        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setLabelFor(contentArea);
        count.setText("Count : " + contentArea.getText().length());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(twitterButton)
                        .addGap(30, 30, 30)
                        .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(emailButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twitterButton)
                    .addComponent(emailButton)
                    .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contentAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contentAreaKeyTyped
        count.setText("Count : " + contentArea.getText().length());
        if(contentArea.getText().length() > 140){
            count.setForeground(Color.red);
        }
        else{
            count.setForeground(Color.black);
        }
    }//GEN-LAST:event_contentAreaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contentArea;
    private javax.swing.JLabel count;
    private javax.swing.JRadioButton emailButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton twitterButton;
    // End of variables declaration//GEN-END:variables

    public JTextArea getContentArea() {
        return contentArea;
    }

    public void setContentArea(JTextArea contentArea) {
        this.contentArea = contentArea;
    }

    public JRadioButton getEmailButton() {
        return emailButton;
    }

    public void setEmailButton(JRadioButton emailButton) {
        this.emailButton = emailButton;
    }

    public JRadioButton getTwitterButton() {
        return twitterButton;
    }

    public void setTwitterButton(JRadioButton twitterButton) {
        this.twitterButton = twitterButton;
    }
}
